<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>MeterService</RootNamespace>
		<AssemblyName>MeterService</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>	
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="FluentValidation.AspNetCore" />
		<PackageReference Include="System.ServiceModel.Http" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Enrichers.Environment" />
		<PackageReference Include="Serilog.Sinks.Seq" />
		<PackageReference Include="Serilog.Sinks.File" />

		<PackageReference Include="Application.Common" />
		<PackageReference Include="Infrastructure.Common" />
		<PackageReference Include="EnergyDashboard.Common" />
		<PackageReference Include="HealthCheck" />
		<PackageReference Include="JobSchedule" />
		<PackageReference Include="MessageBus.Redis" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\notification\src\Notification.Grpc\Notification.Grpc.csproj" />
	  <ProjectReference Include="..\MeterService.gRPC\MeterService.gRPC.csproj" />
	</ItemGroup>

</Project>
