// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Notification.Data.Migrations;

[DbContext(typeof(MessageDbContext))]
partial class MessageDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Notification.Data.MessageEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("Date")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date");

                b.Property<byte?>("MessageScope")
                    .HasColumnType("smallint")
                    .HasColumnName("message_scope");

                b.Property<byte>("MessageType")
                    .HasColumnType("smallint")
                    .HasColumnName("message_type");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("text");

                b.HasKey("Id")
                    .HasName("pk_messages");

                b.HasIndex("Date")
                    .HasDatabaseName("ix_messages_date");

                b.ToTable("messages", (string)null);
            });
#pragma warning restore 612, 618
    }
}
