// <auto-generated />
using MeterFailService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace MeterFailService.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MeterFailService.Domain.Entities.MeterEnergyEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<bool>("Anomaly")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false)
                    .HasColumnName("anomaly");

                b.Property<List<HourEnergy>>("HourEnergys")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("hour_energys");

                b.Property<DateTime>("RecordDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("record_date");

                b.Property<string>("SerialNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("serial_number");

                b.HasKey("Id")
                    .HasName("pk_meter_energys");

                b.ToTable("meter_energys", (string)null);
            });
#pragma warning restore 612, 618
    }
}
