// <auto-generated />
using System;
using EnergyDashboard.Domain.Diagram;
using EnergyDashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyDashboard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DiagramModel>("Diagram")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diagram");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("network_id");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("NetworkId")
                        .HasDatabaseName("ix_areas_network_id");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.DailyEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal>("ExportVar")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("export_var");

                    b.Property<decimal>("ExportWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("export_watt");

                    b.Property<decimal>("ImportVar")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("import_var");

                    b.Property<decimal>("ImportWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("import_watt");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.HasKey("Id")
                        .HasName("pk_daily_energys");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_daily_energys_equipment_id");

                    b.ToTable("daily_energys", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EnergyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal?>("ExportTotalWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("export_total_watt");

                    b.Property<decimal>("ExportVar")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("export_var");

                    b.Property<decimal>("ExportWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("export_watt");

                    b.Property<decimal?>("ImportTotalWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("import_total_watt");

                    b.Property<decimal>("ImportVar")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("import_var");

                    b.Property<decimal>("ImportWatt")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("import_watt");

                    b.Property<DateTimeOffset>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.HasKey("Id")
                        .HasName("pk_energy_profiles");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_energy_profiles_equipment_id");

                    b.ToTable("energy_profiles", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EnergyTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_energy_tariffs");

                    b.ToTable("energy_tariffs", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid?>("BusbarId")
                        .HasColumnType("uuid")
                        .HasColumnName("busbar_id");

                    b.Property<string>("BusbarName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("busbar_name");

                    b.Property<Guid>("CtId")
                        .HasColumnType("uuid")
                        .HasColumnName("ct_id");

                    b.Property<string>("DispatchingCode")
                        .HasColumnType("text")
                        .HasColumnName("dispatching_code");

                    b.Property<string>("IGMCCode")
                        .HasColumnType("text")
                        .HasColumnName("igmc_code");

                    b.Property<int?>("IGMCToolId")
                        .HasColumnType("integer")
                        .HasColumnName("igmc_tool_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Reverse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reverse");

                    b.Property<Guid>("SubstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("substation_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<bool>("Virtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("virtual");

                    b.Property<double>("Voltage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("voltage");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId")
                        .HasDatabaseName("ix_equipment_substation_id");

                    b.ToTable("equipment", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EquipmentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateOfOpereation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_opereation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int>("EquipmentOperationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_operation_type_id");

                    b.Property<Guid>("SubstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("substation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_operations");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_equipment_operations_equipment_id");

                    b.ToTable("equipment_operations", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EquipmentOperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("operation_name");

                    b.HasKey("Id")
                        .HasName("pk_equipment_operation_types");

                    b.ToTable("equipment_operation_types", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.LoadFeederType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_load_feeder_types");

                    b.ToTable("load_feeder_types", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.MeterReadingFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.HasKey("Id")
                        .HasName("pk_meter_reading_failures");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_meter_reading_failures_equipment_id");

                    b.ToTable("meter_reading_failures", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Network", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DiagramModel>("Diagram")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diagram");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_networks");

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.PowerplantOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_powerplant_operators");

                    b.ToTable("powerplant_operators", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.PowerplantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_powerplant_types");

                    b.ToTable("powerplant_types", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Substation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DiagramModel>("Diagram")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diagram");

                    b.Property<DateTimeOffset?>("DismountDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismount_date");

                    b.Property<string>("DispatchingCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dispatching_code");

                    b.Property<string>("IGMCCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("igmc_code");

                    b.Property<int>("IGMCStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("igmc_station_id");

                    b.Property<DateTimeOffset?>("MountDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mount_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_substations");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_substations_zone_id");

                    b.ToTable("substations", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DiagramModel>("Diagram")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diagram");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_zones_area_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.GeneratorFeederEquipment", b =>
                {
                    b.HasBaseType("EnergyDashboard.Domain.Entities.Equipment");

                    b.Property<double?>("Capacity")
                        .HasColumnType("double precision")
                        .HasColumnName("capacity");

                    b.Property<double?>("NominalCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("nominal_capacity");

                    b.Property<int>("PowerplantOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("powerplant_operator_id");

                    b.Property<int>("PowerplantScale")
                        .HasColumnType("integer")
                        .HasColumnName("powerplant_scale");

                    b.Property<int>("PowerplantTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("powerplant_type_id");

                    b.HasIndex("PowerplantOperatorId")
                        .HasDatabaseName("ix_powerplant_feeders_powerplant_operator_id");

                    b.HasIndex("PowerplantTypeId")
                        .HasDatabaseName("ix_powerplant_feeders_powerplant_type_id");

                    b.ToTable("powerplant_feeders", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.LineFeederEquipment", b =>
                {
                    b.HasBaseType("EnergyDashboard.Domain.Entities.Equipment");

                    b.Property<Guid?>("DestinationBusId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_bus_id");

                    b.Property<int>("LineFeederTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("line_feeder_type_id");

                    b.Property<Guid?>("SourceBusId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_bus_id");

                    b.Property<double?>("TransferCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("transfer_capacity");

                    b.Property<Guid>("TransmissionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("transmission_line_id");

                    b.ToTable("line_feeders", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.LoadFeederEquipment", b =>
                {
                    b.HasBaseType("EnergyDashboard.Domain.Entities.Equipment");

                    b.Property<int>("LoadFeederTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("load_feeder_type_id");

                    b.Property<double?>("MaxDemand")
                        .HasColumnType("double precision")
                        .HasColumnName("max_demand");

                    b.HasIndex("LoadFeederTypeId")
                        .HasDatabaseName("ix_load_feeders_load_feeder_type_id");

                    b.ToTable("load_feeders", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.TransformerFeederEquipment", b =>
                {
                    b.HasBaseType("EnergyDashboard.Domain.Entities.Equipment");

                    b.Property<Guid?>("DestinationBusId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_bus_id");

                    b.Property<double?>("MVA")
                        .HasColumnType("double precision")
                        .HasColumnName("mva");

                    b.Property<double?>("PrimaryVoltage")
                        .HasColumnType("double precision")
                        .HasColumnName("primary_voltage");

                    b.Property<double?>("SecondaryVoltage")
                        .HasColumnType("double precision")
                        .HasColumnName("secondary_voltage");

                    b.Property<Guid?>("SourceBusId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_bus_id");

                    b.Property<int>("TransofmerType")
                        .HasColumnType("integer")
                        .HasColumnName("transofmer_type");

                    b.ToTable("transformer_feeders", (string)null);
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Area", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Network", null)
                        .WithMany("Areas")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_areas_networks_network_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.DailyEnergy", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", "Equipment")
                        .WithMany("DailyEnergys")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_energys_equipments_equipment_id");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EnergyProfile", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", "Equipment")
                        .WithMany("EnergyProfiles")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_energy_profiles_equipments_equipment_id");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EnergyTariff", b =>
                {
                    b.OwnsMany("EnergyDashboard.Domain.Entities.EnergyTariffRate", "EnergyTariffRates", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EnergyTariffId")
                                .HasColumnType("uuid")
                                .HasColumnName("energy_tariff_id");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("interval")
                                .HasColumnName("end_time");

                            b1.Property<double>("Rate")
                                .HasColumnType("double precision")
                                .HasColumnName("rate");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("interval")
                                .HasColumnName("start_time");

                            b1.HasKey("Id", "EnergyTariffId")
                                .HasName("pk_energy_tariff_rate");

                            b1.HasIndex("EnergyTariffId")
                                .HasDatabaseName("ix_energy_tariff_rate_energy_tariff_id");

                            b1.ToTable("energy_tariff_rate", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EnergyTariffId")
                                .HasConstraintName("fk_energy_tariff_rate_energy_tariffs_energy_tariff_id");
                        });

                    b.Navigation("EnergyTariffRates");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Substation", "Substation")
                        .WithMany("Equipments")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_substations_substation_id");

                    b.OwnsOne("EnergyDashboard.Domain.ValueObjects.Ratio", "CTRatio", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Primary")
                                .HasColumnType("integer")
                                .HasColumnName("CTRatio.Primary");

                            b1.Property<int>("Secondary")
                                .HasColumnType("integer")
                                .HasColumnName("CTRatio.Secondary");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipment");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId")
                                .HasConstraintName("fk_equipment_equipment_id");
                        });

                    b.OwnsOne("EnergyDashboard.Domain.ValueObjects.Ratio", "PTRatio", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Primary")
                                .HasColumnType("integer")
                                .HasColumnName("PTRatio.Primary");

                            b1.Property<int>("Secondary")
                                .HasColumnType("integer")
                                .HasColumnName("PTRatio.Secondary");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipment");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId")
                                .HasConstraintName("fk_equipment_equipment_id");
                        });

                    b.OwnsMany("EnergyDashboard.Domain.Entities.EquipmentMeter", "EquipmentMeters", b1 =>
                        {
                            b1.Property<string>("SerialNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("serial_number");

                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("equipment_id");

                            b1.Property<bool>("Active")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("active");

                            b1.Property<DateTimeOffset>("DismountDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("dismount_date");

                            b1.Property<DateTimeOffset>("MountDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("mount_date");

                            b1.HasKey("SerialNumber", "EquipmentId")
                                .HasName("pk_equipment_meter");

                            b1.HasIndex("EquipmentId")
                                .HasDatabaseName("ix_equipment_meter_equipment_id");

                            b1.ToTable("equipment_meter", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId")
                                .HasConstraintName("fk_equipment_meter_equipments_equipment_id");
                        });

                    b.Navigation("CTRatio");

                    b.Navigation("EquipmentMeters");

                    b.Navigation("PTRatio");

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.EquipmentOperation", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", null)
                        .WithMany("EquipmentOperations")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_operations_equipments_equipment_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.MeterReadingFailure", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", "Equipment")
                        .WithMany("MeterReadingFailures")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_reading_failures_equipments_equipment_id");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Substation", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Zone", null)
                        .WithMany("Substations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_substations_zones_zone_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Zone", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Area", null)
                        .WithMany("Zones")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_areas_area_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.GeneratorFeederEquipment", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("EnergyDashboard.Domain.Entities.GeneratorFeederEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_powerplant_feeders_equipment_id");

                    b.HasOne("EnergyDashboard.Domain.Entities.PowerplantOperator", "PowerplantOperator")
                        .WithMany()
                        .HasForeignKey("PowerplantOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_powerplant_feeders_powerplant_operators_powerplant_operator");

                    b.HasOne("EnergyDashboard.Domain.Entities.PowerplantType", "PowerplantType")
                        .WithMany()
                        .HasForeignKey("PowerplantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_powerplant_feeders_powerplant_types_powerplant_type_id");

                    b.Navigation("PowerplantOperator");

                    b.Navigation("PowerplantType");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.LineFeederEquipment", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("EnergyDashboard.Domain.Entities.LineFeederEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_feeders_equipment_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.LoadFeederEquipment", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("EnergyDashboard.Domain.Entities.LoadFeederEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_load_feeders_equipment_id");

                    b.HasOne("EnergyDashboard.Domain.Entities.LoadFeederType", "LoadFeederType")
                        .WithMany()
                        .HasForeignKey("LoadFeederTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_load_feeders_load_feeder_types_load_feeder_type_id");

                    b.Navigation("LoadFeederType");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.TransformerFeederEquipment", b =>
                {
                    b.HasOne("EnergyDashboard.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("EnergyDashboard.Domain.Entities.TransformerFeederEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transformer_feeders_equipment_id");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Area", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("DailyEnergys");

                    b.Navigation("EnergyProfiles");

                    b.Navigation("EquipmentOperations");

                    b.Navigation("MeterReadingFailures");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Network", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Substation", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("EnergyDashboard.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Substations");
                });
#pragma warning restore 612, 618
        }
    }
}
