// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeterService.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20220731072307_UpdaateAppDb")]
partial class UpdaateAppDb
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MeterService.Domain.Entities.MeterEnergyEntity", b =>
            {
                b.Property<Guid>("MeterEnergyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("meter_energy_id");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created");

                b.Property<decimal>("EnergyActiveExport")
                    .HasPrecision(18)
                    .HasColumnType("numeric(18,0)")
                    .HasColumnName("energy_active_export");

                b.Property<decimal>("EnergyActiveImport")
                    .HasPrecision(18)
                    .HasColumnType("numeric(18,0)")
                    .HasColumnName("energy_active_import");

                b.Property<decimal>("EnergyReactiveExport")
                    .HasPrecision(18)
                    .HasColumnType("numeric(18,0)")
                    .HasColumnName("energy_reactive_export");

                b.Property<decimal>("EnergyReactiveImport")
                    .HasPrecision(18)
                    .HasColumnType("numeric(18,0)")
                    .HasColumnName("energy_reactive_import");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("last_modified");

                b.Property<int>("MeterId")
                    .HasColumnType("integer")
                    .HasColumnName("meter_id");

                b.Property<DateTimeOffset>("RecordDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("record_date");

                b.Property<int?>("ToolTypeId")
                    .HasColumnType("integer")
                    .HasColumnName("tool_type_id");

                b.HasKey("MeterEnergyId")
                    .HasName("pk_meter_energys");

                b.HasIndex("MeterId")
                    .HasDatabaseName("ix_meter_energys_meter_id");

                b.HasIndex("RecordDate")
                    .HasDatabaseName("ix_meter_energys_record_date");

                b.ToTable("meter_energys", (string)null);
            });

        modelBuilder.Entity("MeterService.Domain.Entities.MeterEntity", b =>
            {
                b.Property<int>("MeterId")
                    .HasColumnType("integer")
                    .HasColumnName("meter_id");

                b.Property<bool>("Active")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false)
                    .HasColumnName("active");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created");

                b.Property<bool>("Dismount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false)
                    .HasColumnName("dismount");

                b.Property<DateTime>("EndOperationDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("end_operation_date");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("last_modified");

                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<string>("SerialNumber")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("serial_number");

                b.Property<DateTime>("StartOperationDate")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("start_operation_date");

                b.Property<int?>("StationId")
                    .HasColumnType("integer")
                    .HasColumnName("station_id");

                b.Property<string>("StationName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("station_name");

                b.HasKey("MeterId")
                    .HasName("pk_meters");

                b.ToTable("meters", (string)null);
            });

        modelBuilder.Entity("MeterService.Domain.Entities.MeterEnergyEntity", b =>
            {
                b.HasOne("MeterService.Domain.Entities.MeterEntity", "Meter")
                    .WithMany("MeterEnergys")
                    .HasForeignKey("MeterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_meter_energys_meters_meter_id");

                b.Navigation("Meter");
            });

        modelBuilder.Entity("MeterService.Domain.Entities.MeterEntity", b =>
            {
                b.Navigation("MeterEnergys");
            });
#pragma warning restore 612, 618
    }
}
